network:
  version: 2
  ethernets:
    enp6s0f0:
      dhcp4: true
    enp6s0f1:
      dhcp4: true
    enp7s0f0:
      dhcp4: no
    enp7s0f1:
      dhcp4: no
  bridges:
    br-lan:
      interfaces: [enp7s0f0, enp7f0f1]
      addresses: [192.168.1.10/24]
      parameters:
        stp: true
      dhcp4: no